### ISSUE TITLE
where to find this paper?

### ISSUE THREAD

**Issue by liamxg** [niemasd/CP2-Paper#1]
@niemasd

**Comment by niemasd** [comment]
https://doi.org/10.1371/journal.pone.0221068

**Comment by liamxg** [comment]
great. thanks for your reply.

**Comment by liamxg** [comment]
do you have a upated version, as I am also very interested about identify clusters.

**Comment by niemasd** [comment]
I'm not sure I understand; a newer version of the paper? That's the published paper, not a preprint or anything

**Comment by liamxg** [comment]
a new version of TreeCluster method. :)

**Comment by niemasd** [comment]
Ah, the newest version is 1.0.3: https://github.com/niemasd/TreeCluster/releases/tag/1.0.3

**Comment by liamxg** [comment]
thanks. I find that you also study HIV. Much same with my projects.
